# Generated by Django 4.0 on 2021-12-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='video',
            field=models.FileField(default='no data', upload_to=''),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='image',
            field=models.ImageField(upload_to='myimages'),
        ),
    ]
